services:
  postgres:
    image: postgres:15
    container_name: medsync_postgres
    environment:
      POSTGRES_DB: medsyncdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGPORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  springapp:
    build: .
    container_name: medsync_spring
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/medsyncdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    restart: unless-stopped
volumes:
  postgres_data: